### ISSUE TITLE
AP metric for the VIP dataset

### ISSUE THREAD

**Issue by 594422814** [Liusifei/UVC#5]
Thanks for releasing this great work!

Can I get the AP^{r}_{vol} score for the VIP dataset using "eval_vip.py"? It seems that only the mIoU score is computed in this file. Do I miss something? Thanks for your help.

**Comment by sunshineatnoon** [comment]
Could you try [this](https://github.com/sunshineatnoon/UVC/blob/jhmdb/eval_instance2.py) file? Command is `python test_mask_vip.py -o results/VIP/category/ --scale_size 560 560 --pre_num 1 -d /DATA/VIP/VIP_Fine/Images/ --val_txt /DATA/VIP/VIP_Fine/lists/val_videos.txt -c weights/checkpoint_latest.pth.tar --topk 50` and then `python eval_instance2.py`

**Comment by 594422814** [comment]
Thanks for your valuable assistance.
